apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  labels: 
    app: frontend
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: frontend
  template: 
    metadata: 
      labels: 
        app: frontend
    spec: 
      containers: 
        - name: frontend-containers
          image: "132866222051.dkr.ecr.us-east-1.amazonaws.com/frontend-image:latest"
          ports: 
            - name: python
              containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports: 
    - port: 80
      targetPort: 80
      protocol: TCP
