apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  labels: 
    app: backend
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: backend
  template: 
    metadata: 
      labels: 
        app: backend
    spec: 
      containers: 
        - name: backend-containers
          image: "132866222051.dkr.ecr.us-east-1.amazonaws.com/backend-image:latest"
          ports: 
            - name: python
              containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports: 
    - port: 80
      targetPort: 5000
      protocol: TCP
